### ISSUE TITLE
'use strict' outside of the IIFE causing other scripts not using strict to stop working

### ISSUE THREAD

**Issue by dannief** [orangehill/bootstrap-session-timeout#11]
Hi,

First, Thanks for your great script. 

I was facing a problem where my site was not working after I deployed. I was getting an error resulting in the use of "use strict" and JavaScript "with". The "with" keyword is being used in another JavaScript library. I realized that the "use strict" statement in bootstrap-session-timeout was outside of the IIFE function and thus made "use strict" global.  I fixed this issue by modifying the script to put the "use script" statement just inside the function.

Please consider updating your repository, so that your script can play well with other scripts that may still be using deprecated JavaScript code.

I will also suggest to the authors of the other library to remove the "with" statement.

Thanks.

**Comment by vedraan** [comment]
Hi, thanks, I'll make sure to fix this with the next release though it might be a week or more since I'm ultra busy atm.
