### ISSUE TITLE
TypeError: $(...).data(...) is undefined

### ISSUE THREAD

**Issue by wongmk4** [orangehill/bootstrap-session-timeout#23]
There is an error found by firebug.
TypeError: $(...).data(...) is undefined
bootstr...eout.js (line 103, col 20)

related statement:
$('#session-timeout-dialog').data('bs.modal').isShown

Maybe add
&& typeof $('#session-timeout-dialog').data('bs.modal') !== 'undefined'     ?

**Comment by Scumtron** [comment]
Someone can fix it?
